In [1]:
from dataset_io import *
from classifiers import *
from algorithm import Algorithm, Predictions
from tqdm import tqdm

In [2]:
#np.save("cross_validated_scenes",cross_validated_scenes())
cross_validated_scenes = np.load("cross_validated_scenes.npy", allow_pickle=True)

### Classifiers evaluation

In [3]:
def evaluate_classifiers():
    grad_metrics=[]
    color_metrics=[]

    for fold in tqdm(cross_validated_scenes):
        train_scenes, test_scenes, fold_name = fold
        print(fold_name)
        acc, prec, rec, f1, _ = classify_gradient(train_scenes, test_scenes, fold_name, True)
        grad_metrics.append([acc, prec, rec, f1])
        res = classify_colors(train_scenes, test_scenes, fold_name, True)
        color_metrics.append(res)

    np.save("color_metrics", color_metrics)
    np.save("grad_metrics", grad_metrics)
    
#evaluate_classifiers()

In [4]:
color_metrics = np.load("color_metrics.npy")
grad_metrics = np.load("grad_metrics.npy")
grad_metrics_avg = np.mean(grad_metrics, 0)
color_metrics_avg = np.mean(color_metrics, 0)
print("color_metrics_avg")
print(color_metrics_avg)
print("grad_metrics_avg")
print(grad_metrics_avg)

color_metrics_avg
[[0.85106473 0.76691145 0.81843552 0.79046445]
 [0.89788648 0.83362693 0.8696812  0.85032493]
 [0.88802002 0.79463581 0.90192808 0.84422685]]
grad_metrics_avg
[0.98093372 0.9983972  0.92963724 0.95946163]


### Algorithms evaluation

In [5]:
def evaluate_algorithm():
    overlaps=[]

    for fold in cross_validated_scenes:
        train_scenes, test_scenes, fold_name = fold
        print(fold_name)
        res_path = Algorithm(train_scenes, test_scenes[2:3], fold_name).run()
        agg_overlaps = Predictions(res_path, test_scenes[2:3]).draw_and_calc()
        print("agg_overlaps",agg_overlaps)
        overlaps.append(agg_overlaps)

    np.save("agg_overlaps", np.mean(overlaps, 0))
    
evaluate_algorithm()

  0%|          | 0/5 [00:00<?, ?it/s]

fold_0


 40%|████      | 2/5 [00:00<00:00, 19.76it/s]

{'max': array([['dark_1', 'IMG_20200228_103440.jpg', 0.1754107079174557,
        (28, 50), 1.0],
       ['dark_1', 'IMG_20200228_103442.jpg', 0.1754107079174557,
        (28, 54), 0.9609375],
       ['dark_1', 'IMG_20200228_103443.jpg', 0.1754107079174557,
        (32, 34), 0.9921875],
       ['dark_1', 'IMG_20200228_103445.jpg', 0.1754107079174557,
        (32, 70), 0.9140625],
       ['dark_1', 'IMG_20200228_103446.jpg', 0.1754107079174557,
        (28, 58), 0.953125]], dtype=object), 'min': array([['dark_1', 'IMG_20200228_103440.jpg', 0.20172231410507405,
        (44, 60), 0.7868421052631579],
       ['dark_1', 'IMG_20200228_103442.jpg', 0.1754107079174557,
        (32, 54), 0.7352631578947368],
       ['dark_1', 'IMG_20200228_103443.jpg', 0.1754107079174557,
        (32, 34), 0.7510526315789474],
       ['dark_1', 'IMG_20200228_103445.jpg', 0.1754107079174557,
        (32, 70), 0.7994736842105263],
       ['dark_1', 'IMG_20200228_103446.jpg', 0.20172231410507405,
        (44, 72), 

 40%|████      | 2/5 [00:00<00:00, 19.73it/s]

IMG_20200228_103446.jpg
[0.6979883040935673]
IMG_20200228_103440.jpg
[0.8869428227226392]
IMG_20200228_103442.jpg
[0.6734152046783626]
IMG_20200228_103443.jpg
[0.7133333333333334]


 60%|██████    | 3/5 [00:00<00:00, 20.79it/s]

IMG_20200228_103445.jpg
[0.6967485380116959]
IMG_20200228_103446.jpg
[0.8434652333734902]
IMG_20200228_103440.jpg
[0.8869428227226392]
IMG_20200228_103442.jpg
[0.6734152046783626]
IMG_20200228_103443.jpg
[0.7133333333333334]


  0%|          | 0/66 [00:00<?, ?it/s]

IMG_20200228_103445.jpg
[0.6967485380116959]
IMG_20200228_103446.jpg
[0.6979883040935673]
agg_overlaps [0.6906269005847954, 0.7627810264239043, 0.7336856405679197]
fold_1


 27%|██▋       | 18/66 [00:40<01:49,  2.27s/it]

KeyboardInterrupt: 

In [ ]:
-1. 4 features per all scenes available
-2. get folds
-3. for each fold set it as test and load features for others (concat)
-4. train classifiers on loaded features
-4.1 test classifiers
5. pass classifiers to algorithm
6. run algorithm to predict single test fold
7. save predictions in list
8. mean of predctions