In [8]:
from dataset_io import *
from classifiers import *
from algorithm import Algorithm
from tqdm import tqdm

In [2]:
#np.save("cross_validated_scenes",cross_validated_scenes())
cross_validated_scenes = np.load("cross_validated_scenes.npy", allow_pickle=True)

### Classifiers evaluation

In [3]:
def evaluate_classifiers():
    grad_metrics=[]
    color_metrics=[]

    for fold in tqdm(cross_validated_scenes):
        train_scenes, test_scenes, fold_name = fold
        print(fold_name)
        acc, prec, rec, f1, _ = classify_gradient(train_scenes, test_scenes, fold_name, True)
        grad_metrics.append([acc, prec, rec, f1])
        res = classify_colors(train_scenes, test_scenes, fold_name, True)
        color_metrics.append(res)

    np.save("color_metrics", color_metrics)
    np.save("grad_metrics", grad_metrics)
    
#evaluate_classifiers()

In [4]:
color_metrics = np.load("color_metrics.npy")
grad_metrics = np.load("grad_metrics.npy")
grad_metrics_avg = np.mean(grad_metrics, 0)
color_metrics_avg = np.mean(color_metrics, 0)
print("color_metrics_avg")
print(color_metrics_avg)
print("grad_metrics_avg")
print(grad_metrics_avg)

color_metrics_avg
[[0.85106473 0.76691145 0.81843552 0.79046445]
 [0.89788648 0.83362693 0.8696812  0.85032493]
 [0.88802002 0.79463581 0.90192808 0.84422685]]
grad_metrics_avg
[0.98093372 0.9983972  0.92963724 0.95946163]


### Algorithms evaluation

In [5]:
def evaluate_algorithm():
    overlaps=[]

    for fold in cross_validated_scenes:
        train_scenes, test_scenes, fold_name = fold
        print(fold_name)
        overlap = Algorithm(train_scenes, test_scenes[:1], fold_name).run()
        print("overlap",overlap)
        overlaps.append(overlap)

    np.save("overlap", np.mean(overlaps))
    
evaluate_algorithm()

  0%|          | 0/88 [00:00<?, ?it/s]

fold_0


  1%|          | 1/88 [00:01<02:24,  1.66s/it]

(26169,) (26169,)
[0.5        0.53684211 0.57947368] [0.0078125 0.015625  0.       ]
(26169,)
[0.5        0.53684211 0.57947368]


  2%|▏         | 2/88 [00:03<02:22,  1.65s/it]

(26169,) (26169,)
[0.62263158 0.61263158 0.57894737] [0.0078125 0.        0.015625 ]
(26169,)
[0.62263158 0.61263158 0.57894737]


  3%|▎         | 3/88 [00:05<02:22,  1.68s/it]

(26169,) (26169,)
[0.44157895 0.43684211 0.44947368] [0. 0. 0.]
(26169,)
[0.44157895 0.43684211 0.44947368]


KeyboardInterrupt: 

In [ ]:
-1. 4 features per all scenes available
-2. get folds
-3. for each fold set it as test and load features for others (concat)
-4. train classifiers on loaded features
-4.1 test classifiers
5. pass classifiers to algorithm
6. run algorithm to predict single test fold
7. save predictions in list
8. mean of predctions